version: '3'
services:
  web:
    image: ghcr.io/supershinyboy/xyzw_web_helper:latest
    container_name: xyzw_web
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf