name: Auto Build and Release

on:
  push:
    tags:
      - 'v*'  # 监听v开头的标签，如v1.0.0
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限：允许创建Release

    steps:
    # 1. 拉取代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 设置Node环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    # 3. 安装依赖
    - name: Install dependencies
      run: npm ci

    # 4. 打包构建
    - name: Build project
      run: npm run build

    # 5. 生成Zip包
    - name: Create zip package
      run: |
        cd dist
        zip -r ../${{ github.event.repository.name }}-${{ github.ref_name }}.zip ./*
        echo "Zip包创建成功！"

    # 6. 创建GitHub Release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          自动化构建版本：${{ github.ref_name }}
          构建时间：${{ github.event.created_at }}
          构建编号：#${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
